#include "cconartist/units.h"

namespace ncore
{
    static const char *unitMap[] = {[UTemperature]         = "°C",
                                    [UFahrenheit]          = "°F",
                                    [UKelvin]              = "K",
                                    [UPressure]            = "hPa",
                                    [UBar]                 = "bar",
                                    [UPascal]              = "Pa",
                                    [UAtmosphere]          = "atm",
                                    [UHumidity]            = "%RH",
                                    [UVelocity]            = "m/s",
                                    [UKilometersPerHour]   = "km/h",
                                    [UMilesPerHour]        = "mph",
                                    [UAcceleration]        = "m/s²",
                                    [UGForce]              = "g",
                                    [UPpm]                 = "ppm",
                                    [UPercent]             = "%",
                                    [UKilograms]           = "kg",
                                    [UGrams]               = "g",
                                    [UMilligrams]          = "mg",
                                    [UMicrograms]          = "µg",
                                    [UTons]                = "t",
                                    [UPounds]              = "lb",
                                    [UOunces]              = "oz",
                                    [UKilometers]          = "km",
                                    [UMeters]              = "m",
                                    [UCentimeters]         = "cm",
                                    [UMillimeters]         = "mm",
                                    [UMiles]               = "mi",
                                    [UFeet]                = "ft",
                                    [UInches]              = "in",
                                    [UHours]               = "h",
                                    [UMinutes]             = "min",
                                    [USeconds]             = "s",
                                    [UMilliseconds]        = "ms",
                                    [UMicroseconds]        = "µs",
                                    [UNanoseconds]         = "ns",
                                    [ULiters]              = "L",
                                    [UMilliliters]         = "mL",
                                    [UCubicMeters]         = "m³",
                                    [UGallons]             = "gal",
                                    [UJoules]              = "J",
                                    [UKiloJoules]          = "kJ",
                                    [UWatts]               = "W",
                                    [UKiloWatts]           = "kW",
                                    [UMegaWatts]           = "MW",
                                    [UKiloWattHour]        = "kWh",
                                    [UBytes]               = "B",
                                    [UKiloBytes]           = "KB",
                                    [UMegaBytes]           = "MB",
                                    [UGigaBytes]           = "GB",
                                    [UTeraBytes]           = "TB",
                                    [UVolt]                = "V",
                                    [UMilliVolt]           = "mV",
                                    [UAmpere]              = "A",
                                    [UMilliAmpere]         = "mA",
                                    [UOhm]                 = "Ω",
                                    [UFarad]               = "F",
                                    [UHenry]               = "H",
                                    [UHertz]               = "Hz",
                                    [UKiloHertz]           = "kHz",
                                    [UMegaHertz]           = "MHz",
                                    [UGigaHertz]           = "GHz",
                                    [UDegrees]             = "°",
                                    [URadians]             = "rad",
                                    [UOnOff]               = "On/Off",
                                    [UOpenClose]           = "Open/Close",
                                    [UTrueFalse]           = "True/False",
                                    [UActiveInactive]      = "Active/Inactive",
                                    [UEnabledDisabled]     = "Enabled/Disabled",
                                    [UStartStop]           = "Start/Stop",
                                    [UAlarmNormal]         = "Alarm/Normal",
                                    [UFaultNormal]         = "Fault/Normal",
                                    [UPresentAbsent]       = "Present/Absent",
                                    [UDetectedNotDetected] = "Detected/Not Detected",
                                    [UUnknown]             = "Unknown"};

    inline const char *unitToString(EPropertyUnit unit)
    {
        if (unit >= 0 && unit < DARRAYSIZE(unitMap) && unitMap[unit] != nullptr)
            return unitMap[unit];
        return "";
    }

}  // namespace ncore
